// <auto-generated />
namespace crudOperation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addDeptListInStuent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDeptListInStuent));
        
        string IMigrationMetadata.Id
        {
            get { return "202202161101500_addDeptListInStuent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
